### ISSUE TITLE
HL-L2370DN (partially) works

### ISSUE THREAD

**Issue by rekado** [pdewacht/brlaser#28]
Thank you very much for this driver!

I used it with the Brother HL-L2370DN on a system with Guix.  While the CUPS test page is printed *without* the image (only the border and the text appear) and CUPS throws an error when trying to print the self test page (see below), I managed to print a monochrome PDF file was generated with LaTeX.

I selected the driver "Brother HL-L2360D series, using brlaser v4 (grayscale, 2-sided printing)".

In case it is of interest, printing the self test page resulted in this error message:

```
Unable to send command to printer driver:
  Unsupported document-format "application/vnd.cups-command
```

Ignoring the failure to print the test pages, the driver really does work, so for the first time in 6 months this printer is more than just a paper weight.  Thanks a lot!

**Comment by pdewacht** [comment]
I'm not sure what the problem is with the test page. I suspect it's some poor interaction between cups and cups-filters. There might be hints in the CUPS error log. brlaser doesn't have a custom test page, so CUPS should generate its default test page.

Can you give the output of this command? With the device-id, CUPS should be able to automatically select the correct driver.

    sudo lpinfo --include-schemes usb -l -v

Also, can you try printing this file? https://static.googleusercontent.com/media/www.google.com/en//landing/cloudprint/testpage.pdf
I've gotten reports that that file doesn't print on the HL-L2300 (as well as many other odd problems, see #4). Since you have a related model, I'm curious if it works for you.

**Comment by rekado** [comment]
Somehow I missed your response!

The device id according to lpinfo is "MFG:Brother;MDL:HL-L2370DN series;CMD:PJL,PCL,PCLXL,URF;".  I only use it as a network printer, so did not limit the output to USB.

The test page was printed successfully.

I recently noticed that the printer does not seem to do anything with *some* documents, such as certain PDF documents.  They do work fine only when rasterized.
